### ISSUE TITLE
reset-password Bad Request

### ISSUE THREAD

**Issue by dbilgin** [janczizikow/timeoff_backend#1]
When making a request to reset the password with `POST /api/auth/reset-password/` if the password is not written in a certain way (like with capital letters etc.), I get back a `400`.
If I can get what the rules are for password resetting I can implement them for the front-end too.

**Comment by janczizikow** [comment]
Right now Django uses the default [password validations](https://docs.djangoproject.com/en/2.2/topics/auth/passwords/#password-validation). The Password should be minimum 8 characters, cannot be only numbers, shouldn't be too similar to the email of the user and shouldn't be one of [common passwords](https://gist.github.com/roycewilliams/281ce539915a947a23db17137d91aeb7)
